### ISSUE TITLE
Test packed packages before publish

### ISSUE THREAD

**Issue by luttje** [luttje/videobrew#22]
I feel like the packages can break in the publishing process. Testing them manually is a hassle.

Since lerna publishes the packages, I want that to pack them before testing. Since [there is no lerna pack command](https://github.com/lerna/lerna/issues/2134), and lerna does more than simply call npm pack: we run [lerna publish](https://github.com/lerna/lerna/tree/main/libs/commands/publish#--registry-url), but with a temporary local npm registry like https://verdaccio.org/docs/what-is-verdaccio or https://github.com/local-npm/local-npm

From there we can install and test all packages, both locally and on ci

## Notes

https://verdaccio.org/docs/best#override-public-packages

```yml
Add a separate entry for this package to config.yaml and remove npmjs from proxy list and restart the server.

packages:
  '@videobrew/*':
    access: $all
    # comment proxy out or leave it empty
    # proxy:
```

https://verdaccio.org/docs/e2e

https://github.com/juanpicado/e2e-ci-example-gh-actions/blob/master/.github/workflows/node.js.yml
